# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3.9'
services:
  # ========================================================================
  # Database Configurations
  # ========================================================================
  # Mongo DB for Catalog API - https://hub.docker.com/_/mongo
  # ------------------------------
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  #  Redis DB for Basket API - https://hub.docker.com/_/redis
  # --------------------------
  basket_redisdb:
    image: redis:alpine
    container_name: basket_redisdb
    restart: always
    ports:
      - '6379:6379'
  # Portainer to monitor docker containers - https://hub.docker.com/r/portainer/portainer-ce
  # Doc: https://documentation.portainer.io/v2.0/deploy/ceinstalldocker/
  # --------------------------
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - 8080:8000
      - 9090:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  #  Postgres DB for Discount API - https://hub.docker.com/_/postgres
  # --------------------------
  discount_postgresdb:
    image: postgres:alpine
    container_name: discount_postgresdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDB
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  #  Postgres DB GUI to maintain the database for Discount API - https://hub.docker.com/r/dpage/pgadmin4
  # --------------------------
  postgresdb_gui:
    image: dpage/pgadmin4
    container_name: postgresdb_gui
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@dotnetmicro.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/root/.pgadmin
  #  Postgres DB GUI to maintain the database for Discount API - https://hub.docker.com/r/dpage/pgadmin4
  # --------------------------
  redisdb_gui:
    image: redislabs/redisinsight
    container_name: redisdb_gui
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - redisinsight_data:/db
  # ========================================================================
  # API Configuration
  # ========================================================================
  # Catalog API
  # ------------
  catalog-api:
    container_name: catalog.api
    image: ${DOCKER_REGISTRAY-}catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=mongodb://catalogdb:27017'
      - 'DatabaseSettings:DatabaseName=ProductDB'
      - 'DatabaseSettings:CollectionName=Products'
    depends_on:
      - catalogdb
    ports:
      - '7000:80'
    build:
      context: .
      dockerfile: services/Catalog/Catalog.API/Dockerfile

  #  Basket API
  # -------------
  basket-api:
    container_name: basket.api
    image: ${DOCKER_REGISTRAY-}basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'CacheSettings:ConnectionString=basket_redisdb:6379'
    depends_on:
      - basket_redisdb
    ports:
      - '7001:80'
    build:
      context: .
      dockerfile: services/Basket/Basket.API/Dockerfile
  # Catalog API
  # ------------
  dicount-api:
    container_name: dicount.api
    image: ${DOCKER_REGISTRAY-}dicountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - 'DatabaseSettings:ConnectionString=Server=discount_postgresdb;Port=5432;Database=DiscountDB;User Id=admin;Password=admin1234;'
    depends_on:
      - discount_postgresdb
    ports:
      - '7002:80'
    build:
      context: .
      dockerfile: services/Discount/Discount.API/Dockerfile
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:
  redisinsight_data:
